// Vue/proyecto-peliculas/src/components/HeaderComponent.vue
<template>
  <header class="header">
    <div class="logo">
      <router-link to="/home" class="logo-link">Movies</router-link>
    </div>
    <nav class="nav">
      <ol class="menu">
        <li class="item-menu"><router-link to="/" class="item-link">Login</router-link></li>
        <li class="item-menu"><router-link to="/" class="item-link">Sing up</router-link></li>
      </ol>
    </nav>
  </header>
</template>
<script>
export default {
  name: 'HeaderComponent'
};
</script>

// react/prueba/src/Components/Header.js
//Dependencies
import React from 'react';

const Header = (props) => {

  return(
    <div className="Header">
      <div className="container">
        <a href="/" className="title">Movies</a>
        <nav className="nav">
          <ul className="menu">
            <li className="item"><a href="/" className="menu_link">Login</a></li>
            <li className="item"><a href="/" className="menu_link select">Sing Up</a></li>
          </ul>
        </nav>
      </div>
    </div>
  );

}

export default Header;
